export const english = {
  language: 'english',
  words: [
    'arrow','balance','battle','beacon','blade','brave','bridge','bright','burst','calm','candle','castle','charge','circle','climb','cloud','comet','control','courage','crystal','dash','defend','drift','echo','ember','energy','falcon','focus','forge','frost','glide','guard','hammer','harbor','impact','iron','jolt','jump','keeper','knight','ladder','legend','lightning','lunar','magnet','march','meteor','mirror','moment','motion','mountain','narrow','nova','ocean','orbit','paddle','phantom','pixel','power','pulse','quick','quiet','rapid','raven','ripple','rocket','shadow','shield','signal','silver','spark','spirit','spring','storm','strike','summit','swift','sword','tactic','thunder','timber','torch','tower','travel','turbo','valley','vector','vigor','vortex','wander','wave','whisper','winter','wisdom','wonder','zephyr','anchor','blossom','copper','dragon','flame','galaxy','hazard','island','jungle','marble','planet','quest','ranger','safari','temple','violet','willow'
  ],
  sentences: [
    'Keep your guard up and stay focused.','Move with purpose across the arena.','A quick dodge can save the round.','Type clearly before the next strike arrives.','The calm fighter sees every opening.','Build a streak to charge your special move.','Counter only when your rival commits.','Fast hands need steady attention.','A shield is strongest at the right moment.','Advance carefully and control the center.','Every correct word earns momentum.','Watch the timer and choose your actions.','The bright arena rewards patient fighters.','A clean command can turn the match around.','Stay light on your feet near danger.','Your next sentence may unlock a special.','Accuracy matters more than frantic typing.','Defend the space between you and danger.','A focused mind makes fewer mistakes.','The final seconds belong to the prepared.','Strike when the opponent drops their guard.','Use movement to create a better angle.','A good counter changes the pace instantly.','Dodge first when a heavy attack is coming.','Keep the rhythm and protect your health.','The arena listens to every keystroke.','Trust your practice and type with intent.','Small commands build a winning streak.','Take the opening before it disappears.','A special attack needs perfect timing.','The strongest fighter adapts quickly.','Stay composed when the score gets close.','Press forward when the path is clear.','Your defense can stop a powerful blow.','One accurate line can decide the round.','Make every letter count in the arena.','The match begins with a single command.','Avoid panic and keep your hands relaxed.','Each successful action changes the battle.','Find the rhythm that keeps you sharp.','A patient dodge is better than a rushed strike.','Protect your health while building pressure.','The arena rewards courage and control.','Quick reactions create surprising victories.','Finish the command before the chance fades.','A steady streak creates real advantage.','Choose your response before the rival acts.','Make space then return with a counter.','The best move is the one you can type cleanly.','Fight smart until the final bell.'
  ]
};

export const hindi = {
  language: 'hindi',
  words: [
    'अग्नि','अंबर','अस्त्र','आकाश','आशा','आवाज','इच्छा','ईमान','उड़ान','उजाला','एकता','ओजस','कदम','कवच','किरण','किला','कौशल','खेल','खुशी','गति','गरज','गाथा','गौरव','चमक','चाल','चोट','चुनौती','जीत','जीवन','ज्वाला','ताकत','तारा','तीर','तूफान','तेज','दिशा','दीपक','दुर्ग','धैर्य','नदी','नायक','निशान','नीति','पथ','पल','पर्वत','पवन','पुकार','पूरा','पैर','प्रहार','बल','बादल','बिजली','बुद्धि','भूमि','भोर','मंच','मित्र','मुकाबला','मुट्ठी','मेघ','युद्ध','यात्रा','रक्षक','रंग','रास्ता','रौशनी','लक्ष्य','लहर','वचन','वज्र','विजय','वीर','वेग','शक्ति','शब्द','शांत','शिखर','शील्ड','सफर','साहस','सितारा','सुरक्षा','सूरज','सेना','सोच','स्मरण','स्वर','हवा','हथियार','हिम्मत','हृदय','हार','आक्रमण','बचाव','चपल','प्रकाश','धनुष','दृढ़','गर्जन','रफ्तार','समय','संकल्प','संकेत','संतुलन','सावधान','स्वप्न','हुनर','हौसला','क्षेत्र','ज्ञान'
  ],
  sentences: [
    'धैर्य रखो और सही समय पर वार करो।','हर अक्षर तुम्हारी ताकत बढ़ाता है।','अपने कवच को तैयार रखो।','तेज गति से मैदान में आगे बढ़ो।','सही बचाव से चोट रुक सकती है।','ध्यान से टाइप करो और जीत पाओ।','तुम्हारा अगला शब्द विशेष वार बना सकता है।','खतरे से बचने के लिए तुरंत हटो।','शांत मन सबसे अच्छा निर्णय लेता है।','लक्ष्य पर नजर रखो और आगे बढ़ो।','हर सही कमांड नया अवसर देती है।','मुकाबले में धैर्य भी एक हथियार है।','सही समय पर जवाबी वार करो।','अपनी गति और संतुलन बनाए रखो।','जीत के लिए हर शब्द महत्वपूर्ण है।','रक्षा करके फिर जोरदार प्रहार करो।','तूफान की तरह तेज लेकिन सावधान रहो।','मैदान के बीच में अपना नियंत्रण रखो।','गलती से घबराओ मत फिर से ध्यान दो।','तुम्हारी लय तुम्हें आगे ले जाएगी।','चमकती रोशनी में भी लक्ष्य साफ रखो।','साहस के साथ सही अक्षर लिखो।','समय खत्म होने से पहले हमला करो।','बचाव तुम्हारे स्वास्थ्य को सुरक्षित रखता है।','शब्द पूरे होते ही शक्ति जागती है।','हर कदम प्रतिद्वंद्वी पर दबाव बनाता है।','तेज उंगलियां और साफ सोच जरूरी हैं।','सही चाल से मुकाबला बदल सकता है।','एकाग्रता से बड़ा कोई कवच नहीं है।','अपनी ऊर्जा को विशेष प्रहार के लिए बचाओ।','हर जीत एक सही शुरुआत से बनती है।','गति बढ़ाओ मगर अक्षर साफ रखो।','तुम्हारा साहस मैदान में चमकेगा।','अंतिम क्षणों में भी हार मत मानो।','सटीक टाइपिंग सबसे मजबूत हथियार है।','प्रहार से पहले प्रतिद्वंद्वी को पढ़ो।','आगे बढ़ो और अपना स्थान बनाओ।','रक्षा और हमला दोनों जरूरी हैं।','हर सही वाक्य तुम्हें मजबूत बनाता है।','चुनौती को स्वीकार करो और डटे रहो।','तुम्हारी तैयारी अब काम आएगी।','शांत रहकर सबसे तेज प्रतिक्रिया दो।','विजय के लिए लगातार आगे बढ़ते रहो।','अक्षरों की शक्ति से लड़ाई जीतो।','सही दिशा में कदम तुम्हें बचाएगा।','मैदान तुम्हारी अगली चाल का इंतजार कर रहा है।','हर प्रहार के बाद अपना कवच संभालो।','लय टूटे तो सांस लो और फिर शुरू करो।','जीतने वाला कभी ध्यान नहीं खोता।','अभी टाइप करो और मुकाबले को बदल दो।'
  ]
};
